### ISSUE TITLE
Cannot read property 'provider' at createUpdateInfoTasks

### ISSUE THREAD

**Issue by rajeshkp** [UniversalDataTool/universal-data-tool#191]
Unable to deploy app into Heroku and it throws the following error "cannot read property 'provider' at createUpdateInfoTasks"

```
remote: -----> Node.js app detected
remote:        
remote: -----> Creating runtime environment
remote:        
remote:        NPM_CONFIG_LOGLEVEL=error
remote:        NODE_ENV=production
remote:        NODE_MODULES_CACHE=true
remote:        NODE_VERBOSE=false
remote:        
remote: -----> Installing binaries
remote:        engines.node (package.json):  unspecified
remote:        engines.npm (package.json):   unspecified (use default)
remote:        
remote:        Resolving node version 12.x...
remote:        Downloading and installing node 12.17.0...
remote:        Using default npm version: 6.14.4
remote:        
remote: -----> Installing dependencies
remote:        Installing node modules
remote:        
remote:        > fsevents@1.2.12 install /tmp/build_cd7c5dcd6d43db5d10b2455edcc1d239/node_modules/@babel/cli/node_modules/fsevents
remote:        > node-gyp rebuild
remote:        
remote:        make: Entering directory '/tmp/build_cd7c5dcd6d43db5d10b2455edcc1d239/node_modules/@babel/cli/node_modules/fsevents/build'
remote:          SOLINK_MODULE(target) Release/obj.target/.node
remote:          COPY Release/.node
remote:        make: Leaving directory '/tmp/build_cd7c5dcd6d43db5d10b2455edcc1d239/node_modules/@babel/cli/node_modules/fsevents/build'
remote:        
remote:        > core-js@2.6.11 postinstall /tmp/build_cd7c5dcd6d43db5d10b2455edcc1d239/node_modules/core-js
remote:        > node -e "try{require('./postinstall')}catch(e){}"
remote:        
remote:        
remote:        > fsevents@1.2.12 install /tmp/build_cd7c5dcd6d43db5d10b2455edcc1d239/node_modules/webpack-dev-server/node_modules/fsevents
remote:        > node-gyp rebuild
remote:        
remote:        make: Entering directory '/tmp/build_cd7c5dcd6d43db5d10b2455edcc1d239/node_modules/webpack-dev-server/node_modules/fsevents/build'
remote:          SOLINK_MODULE(target) Release/obj.target/.node
remote:          COPY Release/.node
remote:        make: Leaving directory '/tmp/build_cd7c5dcd6d43db5d10b2455edcc1d239/node_modules/webpack-dev-server/node_modules/fsevents/build'
remote:        
remote:        > fsevents@1.2.12 install /tmp/build_cd7c5dcd6d43db5d10b2455edcc1d239/node_modules/watchpack/node_modules/fsevents
remote:        > node-gyp rebuild
remote:        
remote:        make: Entering directory '/tmp/build_cd7c5dcd6d43db5d10b2455edcc1d239/node_modules/watchpack/node_modules/fsevents/build'
remote:          SOLINK_MODULE(target) Release/obj.target/.node
remote:          COPY Release/.node
remote:        make: Leaving directory '/tmp/build_cd7c5dcd6d43db5d10b2455edcc1d239/node_modules/watchpack/node_modules/fsevents/build'
remote:        
remote:        > core-js@3.6.5 postinstall /tmp/build_cd7c5dcd6d43db5d10b2455edcc1d239/node_modules/react-app-polyfill/node_modules/core-js
remote:        > node -e "try{require('./postinstall')}catch(e){}"
remote:        
remote:        
remote:        > fsevents@1.2.12 install /tmp/build_cd7c5dcd6d43db5d10b2455edcc1d239/node_modules/jest-haste-map/node_modules/fsevents
remote:        > node-gyp rebuild
remote:        
remote:        make: Entering directory '/tmp/build_cd7c5dcd6d43db5d10b2455edcc1d239/node_modules/jest-haste-map/node_modules/fsevents/build'
remote:          SOLINK_MODULE(target) Release/obj.target/.node
remote:          COPY Release/.node
remote:        make: Leaving directory '/tmp/build_cd7c5dcd6d43db5d10b2455edcc1d239/node_modules/jest-haste-map/node_modules/fsevents/build'
remote:        
remote:        > core-js-pure@3.6.5 postinstall /tmp/build_cd7c5dcd6d43db5d10b2455edcc1d239/node_modules/core-js-pure
remote:        > node -e "try{require('./postinstall')}catch(e){}"
remote:        
remote:        
remote:        > core-js@3.6.5 postinstall /tmp/build_cd7c5dcd6d43db5d10b2455edcc1d239/node_modules/@storybook/codemod/node_modules/core-js
remote:        > node -e "try{require('./postinstall')}catch(e){}"
remote:        
remote:        
remote:        > core-js@3.6.5 postinstall /tmp/build_cd7c5dcd6d43db5d10b2455edcc1d239/node_modules/storybook/node_modules/core-js
remote:        > node -e "try{require('./postinstall')}catch(e){}"
remote:        
remote:        
remote:        > styled-components@4.4.1 postinstall /tmp/build_cd7c5dcd6d43db5d10b2455edcc1d239/node_modules/material-survey/node_modules/styled-components
remote:        > node ./scripts/postinstall.js || exit 0
remote:        
remote:        Use styled-components at work? Consider supporting our development efforts at https://opencollective.com/styled-components
remote:        
remote:        > ffmpeg-static@4.1.1 install /tmp/build_cd7c5dcd6d43db5d10b2455edcc1d239/node_modules/ffmpeg-static
remote:        > node install.js
remote:        
remote:        
remote:        Failed to download the ffmpeg README.
remote:        Failed to download the ffmpeg LICENSE.
remote:        
remote:        > fast-xml-parser@3.16.0 postinstall /tmp/build_cd7c5dcd6d43db5d10b2455edcc1d239/node_modules/fast-xml-parser
remote:        > node tasks/postinstall.js || exit 0
remote:        
remote:        Love fast-xml-parser? Check https://amitkumargupta.work for more projects and contribution.
remote:        
remote:        
remote:        > deasync@0.1.20 install /tmp/build_cd7c5dcd6d43db5d10b2455edcc1d239/node_modules/deasync
remote:        > node ./build.js
remote:        
remote:        `linux-x64-node-12` exists; testing
remote:        Binary is fine; exiting
remote:        
remote:        > fsevents@1.2.13 install /tmp/build_cd7c5dcd6d43db5d10b2455edcc1d239/node_modules/@parcel/watcher/node_modules/fsevents
remote:        > node install.js
remote:        
remote:        
remote:        Skipping 'fsevents' build as platform linux is not supported
remote:        
remote:        > parcel@1.12.4 postinstall /tmp/build_cd7c5dcd6d43db5d10b2455edcc1d239/node_modules/parcel
remote:        > node -e "console.log('\u001b[35m\u001b[1mLove Parcel? You can now donate to our open collective:\u001b[22m\u001b[39m\n > \u001b[34mhttps://opencollective.com/parcel/donate\u001b[0m')"
remote:        
remote:        Love Parcel? You can now donate to our open collective:
remote:         > https://opencollective.com/parcel/donate
remote:        
remote:        > ejs@3.0.2 postinstall /tmp/build_cd7c5dcd6d43db5d10b2455edcc1d239/node_modules/app-builder-lib/node_modules/ejs
remote:        > node --harmony ./postinstall.js
remote:        
remote:        
remote:        > core-js@3.6.5 postinstall /tmp/build_cd7c5dcd6d43db5d10b2455edcc1d239/node_modules/global-agent/node_modules/core-js
remote:        > node -e "try{require('./postinstall')}catch(e){}"
remote:        
remote:        
remote:        > electron@8.2.2 postinstall /tmp/build_cd7c5dcd6d43db5d10b2455edcc1d239/node_modules/electron
remote:        > node install.js
remote:        
remote:        
remote:        > cypress@4.4.0 postinstall /tmp/build_cd7c5dcd6d43db5d10b2455edcc1d239/node_modules/cypress
remote:        > node index.js --exec install
remote:        
remote:        Installing Cypress (version: 4.4.0)
remote:        
remote:        [03:35:49]  Downloading Cypress     [started]
remote:        [03:35:50]  Downloading Cypress      0% 0s [title changed]
remote:        [03:35:50]  Downloading Cypress      3% 3s [title changed]
remote:        [03:35:50]  Downloading Cypress      5% 4s [title changed]
remote:        [03:35:50]  Downloading Cypress      9% 3s [title changed]
remote:        [03:35:50]  Downloading Cypress      12% 3s [title changed]
remote:        [03:35:50]  Downloading Cypress      15% 3s [title changed]
remote:        [03:35:50]  Downloading Cypress      17% 3s [title changed]
remote:        [03:35:50]  Downloading Cypress      20% 3s [title changed]
remote:        [03:35:50]  Downloading Cypress      23% 3s [title changed]
remote:        [03:35:50]  Downloading Cypress      26% 3s [title changed]
remote:        [03:35:51]  Downloading Cypress      28% 3s [title changed]
remote:        [03:35:51]  Downloading Cypress      31% 2s [title changed]
remote:        [03:35:51]  Downloading Cypress      34% 2s [title changed]
remote:        [03:35:51]  Downloading Cypress      37% 2s [title changed]
remote:        [03:35:51]  Downloading Cypress      41% 2s [title changed]
remote:        [03:35:51]  Downloading Cypress      43% 2s [title changed]
remote:        [03:35:51]  Downloading Cypress      47% 2s [title changed]
remote:        [03:35:51]  Downloading Cypress      50% 2s [title changed]
remote:        [03:35:51]  Downloading Cypress      54% 2s [title changed]
remote:        [03:35:51]  Downloading Cypress      57% 1s [title changed]
remote:        [03:35:52]  Downloading Cypress      60% 1s [title changed]
remote:        [03:35:52]  Downloading Cypress      64% 1s [title changed]
remote:        [03:35:52]  Downloading Cypress      67% 1s [title changed]
remote:        [03:35:52]  Downloading Cypress      70% 1s [title changed]
remote:        [03:35:52]  Downloading Cypress      74% 1s [title changed]
remote:        [03:35:52]  Downloading Cypress      77% 1s [title changed]
remote:        [03:35:52]  Downloading Cypress      79% 1s [title changed]
remote:        [03:35:52]  Downloading Cypress      82% 1s [title changed]
remote:        [03:35:52]  Downloading Cypress      86% 0s [title changed]
remote:        [03:35:52]  Downloading Cypress      89% 0s [title changed]
remote:        [03:35:53]  Downloading Cypress      92% 0s [title changed]
remote:        [03:35:53]  Downloading Cypress      99% 0s [title changed]
remote:        [03:35:54]  Downloaded Cypress      [title changed]
remote:        [03:35:54]  Downloaded Cypress      [completed]
remote:        [03:35:54]  Unzipping Cypress       [started]
remote:        [03:35:54]  Unzipping Cypress        0% 0s [title changed]
remote:        [03:35:56]  Unzipping Cypress        1% 219s [title changed]
remote:        [03:35:56]  Unzipping Cypress        1% 220s [title changed]
remote:        [03:35:56]  Unzipping Cypress        1% 221s [title changed]
remote:        [03:35:56]  Unzipping Cypress        1% 222s [title changed]
remote:        [03:35:56]  Unzipping Cypress        1% 223s [title changed]
remote:        [03:35:56]  Unzipping Cypress        1% 224s [title changed]
remote:        [03:35:56]  Unzipping Cypress        1% 225s [title changed]
remote:        [03:35:56]  Unzipping Cypress        1% 226s [title changed]
remote:        [03:35:56]  Unzipping Cypress        1% 227s [title changed]
remote:        [03:35:56]  Unzipping Cypress        1% 228s [title changed]
remote:        [03:35:56]  Unzipping Cypress        1% 229s [title changed]
remote:        [03:35:56]  Unzipping Cypress        2% 113s [title changed]
remote:        [03:35:56]  Unzipping Cypress        2% 114s [title changed]
remote:        [03:35:56]  Unzipping Cypress        2% 115s [title changed]
remote:        [03:35:56]  Unzipping Cypress        2% 116s [title changed]
remote:        [03:35:56]  Unzipping Cypress        2% 117s [title changed]
remote:        [03:35:56]  Unzipping Cypress        2% 118s [title changed]
remote:        [03:35:56]  Unzipping Cypress        2% 119s [title changed]
remote:        [03:35:56]  Unzipping Cypress        3% 78s [title changed]
remote:        [03:35:56]  Unzipping Cypress        3% 79s [title changed]
remote:        [03:35:56]  Unzipping Cypress        3% 80s [title changed]
remote:        [03:35:56]  Unzipping Cypress        3% 81s [title changed]
remote:        [03:35:56]  Unzipping Cypress        3% 82s [title changed]
remote:        [03:35:56]  Unzipping Cypress        4% 61s [title changed]
remote:        [03:35:56]  Unzipping Cypress        4% 62s [title changed]
remote:        [03:35:56]  Unzipping Cypress        4% 63s [title changed]
remote:        [03:35:56]  Unzipping Cypress        4% 64s [title changed]
remote:        [03:35:56]  Unzipping Cypress        5% 50s [title changed]
remote:        [03:35:56]  Unzipping Cypress        5% 51s [title changed]
remote:        [03:35:56]  Unzipping Cypress        5% 52s [title changed]
remote:        [03:35:56]  Unzipping Cypress        5% 53s [title changed]
remote:        [03:35:56]  Unzipping Cypress        5% 54s [title changed]
remote:        [03:35:56]  Unzipping Cypress        6% 44s [title changed]
remote:        [03:35:56]  Unzipping Cypress        6% 45s [title changed]
remote:        [03:35:56]  Unzipping Cypress        6% 46s [title changed]
remote:        [03:35:57]  Unzipping Cypress        7% 39s [title changed]
remote:        [03:35:57]  Unzipping Cypress        7% 40s [title changed]
remote:        [03:35:57]  Unzipping Cypress        7% 41s [title changed]
remote:        [03:35:57]  Unzipping Cypress        7% 42s [title changed]
remote:        [03:35:57]  Unzipping Cypress        8% 36s [title changed]
remote:        [03:35:57]  Unzipping Cypress        8% 37s [title changed]
remote:        [03:35:57]  Unzipping Cypress        8% 38s [title changed]
remote:        [03:35:57]  Unzipping Cypress        9% 33s [title changed]
remote:        [03:35:57]  Unzipping Cypress        9% 34s [title changed]
remote:        [03:35:57]  Unzipping Cypress        10% 30s [title changed]
remote:        [03:35:57]  Unzipping Cypress        10% 31s [title changed]
remote:        [03:35:57]  Unzipping Cypress        11% 28s [title changed]
remote:        [03:35:57]  Unzipping Cypress        11% 29s [title changed]
remote:        [03:35:57]  Unzipping Cypress        12% 27s [title changed]
remote:        [03:35:57]  Unzipping Cypress        13% 25s [title changed]
remote:        [03:35:57]  Unzipping Cypress        13% 26s [title changed]
remote:        [03:35:57]  Unzipping Cypress        14% 24s [title changed]
remote:        [03:35:58]  Unzipping Cypress        15% 23s [title changed]
remote:        [03:35:58]  Unzipping Cypress        16% 21s [title changed]
remote:        [03:35:58]  Unzipping Cypress        16% 22s [title changed]
remote:        [03:35:58]  Unzipping Cypress        17% 21s [title changed]
remote:        [03:35:58]  Unzipping Cypress        18% 20s [title changed]
remote:        [03:35:58]  Unzipping Cypress        19% 19s [title changed]
remote:        [03:35:58]  Unzipping Cypress        19% 20s [title changed]
remote:        [03:35:58]  Unzipping Cypress        20% 18s [title changed]
remote:        [03:35:58]  Unzipping Cypress        20% 19s [title changed]
remote:        [03:35:58]  Unzipping Cypress        21% 18s [title changed]
remote:        [03:35:58]  Unzipping Cypress        22% 17s [title changed]
remote:        [03:35:58]  Unzipping Cypress        23% 16s [title changed]
remote:        [03:35:59]  Unzipping Cypress        23% 17s [title changed]
remote:        [03:35:59]  Unzipping Cypress        24% 16s [title changed]
remote:        [03:35:59]  Unzipping Cypress        25% 15s [title changed]
remote:        [03:35:59]  Unzipping Cypress        25% 16s [title changed]
remote:        [03:35:59]  Unzipping Cypress        26% 15s [title changed]
remote:        [03:35:59]  Unzipping Cypress        27% 15s [title changed]
remote:        [03:35:59]  Unzipping Cypress        28% 14s [title changed]
remote:        [03:35:59]  Unzipping Cypress        28% 15s [title changed]
remote:        [03:35:59]  Unzipping Cypress        29% 14s [title changed]
remote:        [03:35:59]  Unzipping Cypress        30% 13s [title changed]
remote:        [03:35:59]  Unzipping Cypress        30% 14s [title changed]
remote:        [03:35:59]  Unzipping Cypress        31% 13s [title changed]
remote:        [03:36:00]  Unzipping Cypress        32% 13s [title changed]
remote:        [03:36:00]  Unzipping Cypress        33% 13s [title changed]
remote:        [03:36:00]  Unzipping Cypress        34% 12s [title changed]
remote:        [03:36:00]  Unzipping Cypress        34% 13s [title changed]
remote:        [03:36:01]  Unzipping Cypress        34% 15s [title changed]
remote:        [03:36:01]  Unzipping Cypress        35% 14s [title changed]
remote:        [03:36:01]  Unzipping Cypress        36% 14s [title changed]
remote:        [03:36:01]  Unzipping Cypress        37% 13s [title changed]
remote:        [03:36:01]  Unzipping Cypress        38% 13s [title changed]
remote:        [03:36:02]  Unzipping Cypress        39% 12s [title changed]
remote:        [03:36:02]  Unzipping Cypress        39% 13s [title changed]
remote:        [03:36:02]  Unzipping Cypress        40% 12s [title changed]
remote:        [03:36:02]  Unzipping Cypress        41% 12s [title changed]
remote:        [03:36:02]  Unzipping Cypress        42% 11s [title changed]
remote:        [03:36:02]  Unzipping Cypress        43% 11s [title changed]
remote:        [03:36:02]  Unzipping Cypress        44% 11s [title changed]
remote:        [03:36:02]  Unzipping Cypress        45% 10s [title changed]
remote:        [03:36:02]  Unzipping Cypress        46% 10s [title changed]
remote:        [03:36:02]  Unzipping Cypress        47% 10s [title changed]
remote:        [03:36:02]  Unzipping Cypress        48% 9s [title changed]
remote:        [03:36:02]  Unzipping Cypress        48% 10s [title changed]
remote:        [03:36:02]  Unzipping Cypress        49% 9s [title changed]
remote:        [03:36:02]  Unzipping Cypress        50% 9s [title changed]
remote:        [03:36:03]  Unzipping Cypress        51% 9s [title changed]
remote:        [03:36:03]  Unzipping Cypress        52% 8s [title changed]
remote:        [03:36:03]  Unzipping Cypress        53% 8s [title changed]
remote:        [03:36:03]  Unzipping Cypress        54% 8s [title changed]
remote:        [03:36:03]  Unzipping Cypress        55% 8s [title changed]
remote:        [03:36:03]  Unzipping Cypress        56% 7s [title changed]
remote:        [03:36:03]  Unzipping Cypress        57% 7s [title changed]
remote:        [03:36:03]  Unzipping Cypress        58% 7s [title changed]
remote:        [03:36:03]  Unzipping Cypress        59% 7s [title changed]
remote:        [03:36:03]  Unzipping Cypress        60% 6s [title changed]
remote:        [03:36:03]  Unzipping Cypress        60% 7s [title changed]
remote:        [03:36:03]  Unzipping Cypress        61% 6s [title changed]
remote:        [03:36:03]  Unzipping Cypress        62% 6s [title changed]
remote:        [03:36:03]  Unzipping Cypress        63% 6s [title changed]
remote:        [03:36:04]  Unzipping Cypress        64% 6s [title changed]
remote:        [03:36:04]  Unzipping Cypress        65% 5s [title changed]
remote:        [03:36:04]  Unzipping Cypress        65% 6s [title changed]
remote:        [03:36:04]  Unzipping Cypress        100% 0s [title changed]
remote:        [03:36:04]  Unzipped Cypress        [title changed]
remote:        [03:36:04]  Unzipped Cypress        [completed]
remote:        [03:36:04]  Finishing Installation  [started]
remote:        [03:36:04]  Finished Installation   /app/.cache/Cypress/4.4.0 [title changed]
remote:        [03:36:04]  Finished Installation   /app/.cache/Cypress/4.4.0 [completed]
remote:        
remote:        You can now open Cypress by running: node_modules/.bin/cypress open
remote:        
remote:        https://on.cypress.io/installing-cypress
remote:        
remote:        
remote:        > core-js@3.6.5 postinstall /tmp/build_cd7c5dcd6d43db5d10b2455edcc1d239/node_modules/@storybook/api/node_modules/core-js
remote:        > node -e "try{require('./postinstall')}catch(e){}"
remote:        
remote:        
remote:        > core-js@3.6.5 postinstall /tmp/build_cd7c5dcd6d43db5d10b2455edcc1d239/node_modules/@storybook/theming/node_modules/core-js
remote:        > node -e "try{require('./postinstall')}catch(e){}"
remote:        
remote:        
remote:        > core-js@3.6.5 postinstall /tmp/build_cd7c5dcd6d43db5d10b2455edcc1d239/node_modules/@storybook/client-logger/node_modules/core-js
remote:        > node -e "try{require('./postinstall')}catch(e){}"
remote:        
remote:        
remote:        > core-js@3.6.5 postinstall /tmp/build_cd7c5dcd6d43db5d10b2455edcc1d239/node_modules/@storybook/router/node_modules/core-js
remote:        > node -e "try{require('./postinstall')}catch(e){}"
remote:        
remote:        
remote:        > core-js@3.6.5 postinstall /tmp/build_cd7c5dcd6d43db5d10b2455edcc1d239/node_modules/@storybook/core-events/node_modules/core-js
remote:        > node -e "try{require('./postinstall')}catch(e){}"
remote:        
remote:        
remote:        > core-js@3.6.5 postinstall /tmp/build_cd7c5dcd6d43db5d10b2455edcc1d239/node_modules/@storybook/channels/node_modules/core-js
remote:        > node -e "try{require('./postinstall')}catch(e){}"
remote:        
remote:        
remote:        > core-js@3.6.5 postinstall /tmp/build_cd7c5dcd6d43db5d10b2455edcc1d239/node_modules/@storybook/addons/node_modules/core-js
remote:        > node -e "try{require('./postinstall')}catch(e){}"
remote:        
remote:        
remote:        > fsevents@1.2.13 install /tmp/build_cd7c5dcd6d43db5d10b2455edcc1d239/node_modules/@storybook/react/node_modules/fsevents
remote:        > node install.js
remote:        
remote:        
remote:        Skipping 'fsevents' build as platform linux is not supported
remote:        
remote:        > core-js@3.6.5 postinstall /tmp/build_cd7c5dcd6d43db5d10b2455edcc1d239/node_modules/@storybook/react/node_modules/core-js
remote:        > node -e "try{require('./postinstall')}catch(e){}"
remote:        
remote:        
remote:        > core-js@3.6.5 postinstall /tmp/build_cd7c5dcd6d43db5d10b2455edcc1d239/node_modules/@storybook/node-logger/node_modules/core-js
remote:        > node -e "try{require('./postinstall')}catch(e){}"
remote:        
remote:        
remote:        > core-js@3.6.5 postinstall /tmp/build_cd7c5dcd6d43db5d10b2455edcc1d239/node_modules/@storybook/channel-postmessage/node_modules/core-js
remote:        > node -e "try{require('./postinstall')}catch(e){}"
remote:        
remote:        
remote:        > fsevents@1.2.13 install /tmp/build_cd7c5dcd6d43db5d10b2455edcc1d239/node_modules/@storybook/core/node_modules/fsevents
remote:        > node install.js
remote:        
remote:        
remote:        Skipping 'fsevents' build as platform linux is not supported
remote:        
remote:        > core-js@3.6.5 postinstall /tmp/build_cd7c5dcd6d43db5d10b2455edcc1d239/node_modules/lazy-universal-dotenv/node_modules/core-js
remote:        > node -e "try{require('./postinstall')}catch(e){}"
remote:        
remote:        
remote:        > ejs@2.7.4 postinstall /tmp/build_cd7c5dcd6d43db5d10b2455edcc1d239/node_modules/ejs
remote:        > node ./postinstall.js
remote:        
remote:        
remote:        > core-js@3.6.5 postinstall /tmp/build_cd7c5dcd6d43db5d10b2455edcc1d239/node_modules/@storybook/core/node_modules/core-js
remote:        > node -e "try{require('./postinstall')}catch(e){}"
remote:        
remote:        
remote:        > core-js@3.6.5 postinstall /tmp/build_cd7c5dcd6d43db5d10b2455edcc1d239/node_modules/simplebar/node_modules/core-js
remote:        > node -e "try{require('./postinstall')}catch(e){}"
remote:        
remote:        
remote:        > core-js@3.6.5 postinstall /tmp/build_cd7c5dcd6d43db5d10b2455edcc1d239/node_modules/@storybook/components/node_modules/core-js
remote:        > node -e "try{require('./postinstall')}catch(e){}"
remote:        
remote:        
remote:        > core-js@3.6.5 postinstall /tmp/build_cd7c5dcd6d43db5d10b2455edcc1d239/node_modules/@storybook/ui/node_modules/core-js
remote:        > node -e "try{require('./postinstall')}catch(e){}"
remote:        
remote:        
remote:        > core-js@3.6.5 postinstall /tmp/build_cd7c5dcd6d43db5d10b2455edcc1d239/node_modules/@storybook/client-api/node_modules/core-js
remote:        > node -e "try{require('./postinstall')}catch(e){}"
remote:        
remote:        
remote:        > core-js@3.6.5 postinstall /tmp/build_cd7c5dcd6d43db5d10b2455edcc1d239/node_modules/@storybook/addon-links/node_modules/core-js
remote:        > node -e "try{require('./postinstall')}catch(e){}"
remote:        
remote:        
remote:        > core-js@3.6.5 postinstall /tmp/build_cd7c5dcd6d43db5d10b2455edcc1d239/node_modules/@storybook/addon-actions/node_modules/core-js
remote:        > node -e "try{require('./postinstall')}catch(e){}"
remote:        
remote:        
remote:        > universal-data-tool@0.10.17 postinstall /tmp/build_cd7c5dcd6d43db5d10b2455edcc1d239
remote:        > electron-builder install-app-deps
remote:        
remote:          • electron-builder  version=22.5.1
remote:          • loaded configuration  file=package.json ("build" field)
remote:          • rebuilding native dependencies  dependencies=fsevents@1.2.12, fsevents@1.2.12, fsevents@1.2.12 platform=linux arch=x64
remote:        added 3552 packages in 108.031s
remote:        
remote: -----> Build
remote:        Running build
remote:        
remote:        > universal-data-tool@0.10.17 build /tmp/build_cd7c5dcd6d43db5d10b2455edcc1d239
remote:        > npm run build:babel && npm run build:vanilla && npm run build:desktop
remote:        
remote:        
remote:        > universal-data-tool@0.10.17 build:babel /tmp/build_cd7c5dcd6d43db5d10b2455edcc1d239
remote:        > cross-env NODE_ENV=production babel ./src --out-dir=./lib && cp ./package.json ./lib/package.json && node ./lib/lib/fix-deps.js
remote:        
remote:        Successfully compiled 165 files with Babel.
remote:        
remote:        > universal-data-tool@0.10.17 build:vanilla /tmp/build_cd7c5dcd6d43db5d10b2455edcc1d239
remote:        > parcel build -d ./lib -o vanilla.js ./src/vanilla/index.js
remote:        
remote: lscpu: failed to determine number of CPUs: /sys/devices/system/cpu/possible: No such file or directory
remote:        ⚠️  Could not load source file "../src/index.ts" in source map of "../../node_modules/use-event-callback/lib/index.js".
remote:        ✨  Built in 74.21s.
remote:        
remote:        lib/vanilla.js.map     ⚠️  6.16 MB     933ms
remote:        lib/vanilla.js         ⚠️  2.91 MB    72.61s
remote:        lib/vanilla.css.map         197 B       3ms
remote:        lib/vanilla.css              88 B     4.99s
remote:        
remote:        > universal-data-tool@0.10.17 build:desktop /tmp/build_cd7c5dcd6d43db5d10b2455edcc1d239
remote:        > cross-env REACT_APP_DESKTOP=true PUBLIC_URL=./ react-scripts build && electron-builder build && cp ./desktop/entitlements.mac.plist ./build/entitlements.mac.plist
remote:        
remote:        Creating an optimized production build...
remote:        Compiled successfully.
remote:        
remote:        File sizes after gzip:
remote:        
remote:          899.64 KB  build/static/js/2.42fc4f08.chunk.js
remote:          53.4 KB    build/static/js/main.35683a21.chunk.js
remote:          785 B      build/static/js/runtime-main.7764971b.js
remote:          176 B      build/static/css/main.f0385375.chunk.css
remote:        
remote:        The project was built assuming it is hosted at ./.
remote:        You can control this with the homepage field in your package.json.
remote:        
remote:        The build folder is ready to be deployed.
remote:        
remote:        Find out more about deployment here:
remote:        
remote:          bit.ly/CRA-deploy
remote:        
remote:          • electron-builder  version=22.5.1 os=4.4.0-1066-aws
remote:          • loaded configuration  file=package.json ("build" field)
remote:          • description is missed in the package.json  appPackageFile=/tmp/build_cd7c5dcd6d43db5d10b2455edcc1d239/package.json
remote:          • author is missed in the package.json  appPackageFile=/tmp/build_cd7c5dcd6d43db5d10b2455edcc1d239/package.json
remote:          • rebuilding native dependencies  dependencies=fsevents@1.2.12, fsevents@1.2.12, fsevents@1.2.12 platform=linux arch=x64
remote:          • packaging       platform=linux arch=x64 electron=8.2.2 appOutDir=dist/linux-unpacked
remote:          • downloading     url=https://github.com/electron/electron/releases/download/v8.2.2/electron-v8.2.2-linux-x64.zip size=71 MB parts=4
remote:          • downloaded      url=https://github.com/electron/electron/releases/download/v8.2.2/electron-v8.2.2-linux-x64.zip duration=954ms
remote:          • building        target=AppImage arch=x64 file=dist/Universal Data Tool-0.10.17.AppImage
remote:          • Cannot detect repository by .git/config. Please specify "repository" in the package.json (https://docs.npmjs.com/files/package.json#repository).
remote:        Please see https://electron.build/configuration/publish
remote:          • default Electron icon is used  reason=application icon is not set
remote:          • downloading     url=https://github.com/electron-userland/electron-builder-binaries/releases/download/appimage-12.0.1/appimage-12.0.1.7z size=1.6 MB parts=1
remote:          • downloaded      url=https://github.com/electron-userland/electron-builder-binaries/releases/download/appimage-12.0.1/appimage-12.0.1.7z duration=838ms
remote:          • Cannot detect repository by .git/config. Please specify "repository" in the package.json (https://docs.npmjs.com/files/package.json#repository).
remote:        Please see https://electron.build/configuration/publish
remote:          ⨯ Cannot read property 'provider' of null  stackTrace=
remote:                                                       TypeError: Cannot read property 'provider' of null
remote:                                                           at createUpdateInfoTasks (/tmp/build_cd7c5dcd6d43db5d10b2455edcc1d239/node_modules/app-builder-lib/src/publish/updateInfoBuilder.ts:110:44)
remote:                                                           at async Promise.all (index 0)
remote:                                                           at AsyncTaskManager.awaitTasks (/tmp/build_cd7c5dcd6d43db5d10b2455edcc1d239/node_modules/builder-util/src/asyncTaskManager.ts:65:25)
remote:                                                           at PublishManager.awaitTasks (/tmp/build_cd7c5dcd6d43db5d10b2455edcc1d239/node_modules/app-builder-lib/src/publish/PublishManager.ts:210:5)
remote:                                                           at executeFinally (/tmp/build_cd7c5dcd6d43db5d10b2455edcc1d239/node_modules/builder-util/src/promise.ts:25:3)
remote: npm ERR! code ELIFECYCLE
remote: npm ERR! errno 1
remote: npm ERR! universal-data-tool@0.10.17 build:desktop: `cross-env REACT_APP_DESKTOP=true PUBLIC_URL=./ react-scripts build && electron-builder build && cp ./desktop/entitlements.mac.plist ./build/entitlements.mac.plist`
remote: npm ERR! Exit status 1
remote: npm ERR! 
remote: npm ERR! Failed at the universal-data-tool@0.10.17 build:desktop script.
remote: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
remote: 
remote: npm ERR! A complete log of this run can be found in:
remote: npm ERR!     /tmp/npmcache.bsyR9/_logs/2020-05-29T03_43_06_747Z-debug.log
remote: npm ERR! code ELIFECYCLE
remote: npm ERR! errno 1
remote: npm ERR! universal-data-tool@0.10.17 build: `npm run build:babel && npm run build:vanilla && npm run build:desktop`
remote: npm ERR! Exit status 1
remote: npm ERR! 
remote: npm ERR! Failed at the universal-data-tool@0.10.17 build script.
remote: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
remote: 
remote: npm ERR! A complete log of this run can be found in:
remote: npm ERR!     /tmp/npmcache.bsyR9/_logs/2020-05-29T03_43_06_960Z-debug.log
remote: 
remote: -----> Build failed
remote:        
remote:        We're sorry this build is failing! You can troubleshoot common issues here:
remote:        https://devcenter.heroku.com/articles/troubleshooting-node-deploys
remote:        
remote:        Some possible problems:
remote:        
remote:        - Node version not specified in package.json
remote:          https://devcenter.heroku.com/articles/nodejs-support#specifying-a-node-js-version
remote:        
remote:        Love,
remote:        Heroku
remote:        
remote:  !     Push rejected, failed to compile Node.js app.
remote: 
remote:  !     Push failed
remote: Verifying deploy...
remote: 

```

**Comment by seveibar** [comment]
Hey @rajeshkp, could you walk me through the steps you used to deploy the application:?

**Comment by seveibar** [comment]
@puskuruk noticed that you might be building the desktop app on the server, I'm not sure why you would want to do that

**Comment by rajeshkp** [comment]
The intention was to deploy the web app to Heroku. Just checked out the master branch and did a deploy (git push heroku master) and it fails with the above error. What am I missing here?

**Comment by seveibar** [comment]
We aren't currently set up to deploy to Heroku.
