### ISSUE TITLE
Crash with simple text classification task

### ISSUE THREAD

**Issue by nopper** [UniversalDataTool/universal-data-tool#337]
I am not sure if this is due to text classification being multi label or if there's something wrong with the file format.

This is the minimal example file to reproduce the bug. Save this file to `whatever.json`.

```json
{
    "name": "whatever",
    "interface": {
        "type": "text_classification",
        "labels": [
            {"id": "a"},
            {"id": "b"}
        ],
        "multiple": true
    },
    "samples": [
        {
            "_id": "test",
            "document": "test"
        }
    ]
}
```

Steps to reproduce:

1. Navigate to udt.dev
2. Click on "Open File"
3. Select `whatever.json` and click ok.
4. Click on label and crash!

This is the stacktrace:

```
TypeError: Cannot read property 'hasAnnotation' of undefined
    at https://udt.dev/app/static/js/main.74e5e70d.chunk.js:1:61921
    at Array.map (<anonymous>)
    at to (https://udt.dev/app/static/js/main.74e5e70d.chunk.js:1:61836)
    at Go (https://udt.dev/app/static/js/2.b4898d5d.chunk.js:2:2474042)
    at ms (https://udt.dev/app/static/js/2.b4898d5d.chunk.js:2:2520448)
    at lc (https://udt.dev/app/static/js/2.b4898d5d.chunk.js:2:2512981)
    at sc (https://udt.dev/app/static/js/2.b4898d5d.chunk.js:2:2512906)
    at Zs (https://udt.dev/app/static/js/2.b4898d5d.chunk.js:2:2509915)
    at https://udt.dev/app/static/js/2.b4898d5d.chunk.js:2:2461300
    at t.unstable_runWithPriority (https://udt.dev/app/static/js/2.b4898d5d.chunk.js:2:2536881)
    at $i (https://udt.dev/app/static/js/2.b4898d5d.chunk.js:2:2461009)
    at Vi (https://udt.dev/app/static/js/2.b4898d5d.chunk.js:2:2461245)
    at qi (https://udt.dev/app/static/js/2.b4898d5d.chunk.js:2:2461180)
    at F (https://udt.dev/app/static/js/2.b4898d5d.chunk.js:2:2530646)
    at Yt (https://udt.dev/app/static/js/2.b4898d5d.chunk.js:2:2438661)
    at HTMLDocument.o (https://udt.dev/app/static/js/2.b4898d5d.chunk.js:2:135449)
```

**Comment by seveibar** [comment]
Your JSON looks fine, are you using 0.14? This release was pretty big and probably introduced some minor errors!

**Comment by seveibar** [comment]
This was actually working for me when I directly pasted the JSON into the Setup page. So might be related to file importing?
![image](https://user-images.githubusercontent.com/1910070/96910800-fe937700-146d-11eb-8808-a12731463d48.png)
